// https://hrweb.berkeley.edu/sites/default/files/attachments/action-verbs.pdf
var action_words = ['administer','analyze','assign','attain','consolidate','contract','coordinate','delegate','evaluate','execute','improve','increase','oversaw','prioritize','produce','recommend','review','schedule','strengthen','supervise','address','arbitrate','author','collaborate','convince','correspond','draft','edit','enlist','formulate','influence','interpret','lecture','mediate','moderate','negotiate','persuade','promote','publicize','reconcile','recruit','spoke','translate','wrote','clarified','collect','critique','diagnose','evaluate','examine','extract','identified','inspect','interpret','interview','investigate','organize','review','summarize','survey','systematize','assemble','built','calculate','compute','devise','engineer','fabricate','maintain','operate','overhaul','programm','remodel','repair','solve','upgrade','adapt','advise','clarified','communicate','coordinate','demystified','enable','encourage','evaluate','explain','inform','instruct','persuade','goals','stimulate','train','administer','allocate','analyze','appraise','audit','balance','budget','calculate','compute','forecast','manage','market','project','research','acted','conceptualize','create','customize','design','develop','direct','establish','fashion','found','illustrate','initiate','institute','integrate','introduce','invent','originate','perform','planned','revitalize','shape','assess','assist','clarified','coach','counsel','demonstrate','diagnose','expedite','facilitate','familiarize','guide','motivate','referred','rehabilitate','represent','approve','arrange','catalogue','classified','collect','compile','dispatch','execute','generate','implement','inspect','monitor','operate','prepare','process','purchase','record','retrieve','screen','specified','systematize','tabulate','validate','achieve','expand','improve','pioneer','reduce','resolve','restore','spearhead','transform','angular','challenge','github','portfolio','website','safely','informing','information','environment','assistance','suggestion','fundamental','programming','javascript','educate','arduino','precision','simplified','implementation','calculate','utilize','function','approximate','arithmetic','algorithm','HTTP','interface','implement','closed-loop PD controller','functionality','dynamic','visualizer','iterate','triangular','Delaunay Triangulation','random','OpenSimplex','HSV gradient','manipulation','GUI']
var re = new RegExp('\\b(' + action_words.join('|') + ')(s|ly|d|ed)?\\b', 'gi')
// https://www.telerik.com/blogs/highlight-text-within-string-using-angular-regular-expressions
export function highlight(content: string) {
    if (!content) {
        return content;
    }
    return content.replace(re, match => {
        return '<span class="text-success">' + match + '</span>';
    })
}