// https://hrweb.berkeley.edu/sites/default/files/attachments/action-verbs.pdf
var action_words = ['administered','analyzed','assigned','attained','chaired','consolidated','contracted','coordinated','delegated','developed','directed','evaluated','executed','improved','increased','organized','oversaw','planned','prioritized','produced','recommended','reviewed','scheduled','strengthened','supervised','addressed','arbitrated','arranged','authored','collaborated','convinced','corresponded','developed','directed','drafted','edited','enlisted','formulated','influenced','interpreted','lectured','mediated','moderated','negotiated','persuaded','promoted','publicized','reconciled','recruited','spoke','translated','wrote','clarified','collected','critiqued','diagnosed','evaluated','examined','extracted','identified','inspected','interpreted','interviewed','investigated','organized','reviewed','summarized','surveyed','systematized','assembled','built','calculated','computed','designed','devised','engineered','fabricated','maintained','operated','overhauled','programmed','remodeled','repaired','solved','upgraded','adapted','advised','clarified','coached','communicated','coordinated','demystified','developed','enabled','encouraged','evaluated','explained','facilitated','guided','informed','instructed','persuaded','goals','stimulated','trained','administered','allocated','analyzed','appraised','audited','balanced','budgeted','calculated','computed','developed','forecasted','managed','marketed','planned','projected','researched','acted','conceptualized','created','customized','designed','developed','directed','established','fashioned','founded','illustrated','initiated','instituted','integrated','introduced','invented','originated','performed','planned','revitalized','shaped','assessed','assisted','clarified','coached','counseled','demonstrated','diagnosed','educated','expedited','facilitated','familiarized','guided','motivated','referred','rehabilitated','represented','approved','arranged','catalogued','classified','collected','compiled','dispatched','executed','generated','implemented','inspected','monitored','operated','organized','prepared','processed','purchased','recorded','retrieved','screened','specified','systematized','tabulated','validated','achieved','expanded','improved','pioneered','reduced','resolved','restored','spearheaded','transformed', 'angular', 'challenge', 'github', 'portfolio', 'website', 'safely', 'informing', 'information', 'environment', 'assistance', 'suggestions', 'fundamentals', 'programming', 'javascript', 'educate', 'arduino', 'precision', 'simplified', 'implementation', 'calculate', 'utilized', 'functions', 'approximated', 'arithmetic', 'algorithm', 'HTTP', 'interface', 'implement', 'closed-loop PD controller', 'functionality', 'dynamic', 'visualizer', 'iterated', ]
var re = new RegExp('(' + action_words.join('|') + ')(s)?', 'gi')
// https://www.telerik.com/blogs/highlight-text-within-string-using-angular-regular-expressions
export function highlight(content: string) {
    if (!content) {
        return content;
    }
    return content.replace(re, match => {
        return '<span class="text-success">' + match + '</span>';
    })
}